### ISSUE TITLE
Is this alive? Re. Luminus / lib-noir

### ISSUE THREAD

**Issue by hjrnunes** [ddellacosta/friend-oauth2#35]
Hey @ddellacosta are you still maintaining this?

Anyway, I've been struggling to find a way to integrate Friend/Friend-oauth2 with Luminus. The problem being the way lib-noir handles the middleware and the fact that it wouldn't redirect to authorization if :allow-anon? is true, and instead just bubble up the unauthorized exception.

So, after many hours combing the web I finally found that @bzg had the same problem on the Clojure mailing list and posed the question but nobody answered. However, I sniffed around his repositories and found out that he'd indeed found out what to do - thanks @bzg :)

So here it is for posterity, in it's glorious simplicity:

Instead of:
```clojure
(defroutes routes ;;etc)

(def app
  (handler/site
   (friend/authenticate routes
    {:allow-anon? true
     :workflows [(oauth2/workflow
                  {:client-config client-config
                   :uri-config uri-config
                   :access-token-parsefn get-access-token-from-params
                   :config-auth config-auth})]})))
```
which is everything you'll ever see in every post and comment about it, do:

```clojure
(defroutes routes ...)

(def app
  (app-handler
    [auth-routes (friend/authenticate home-routes friend-config) base-routes]
    :middleware (load-middleware)
    ;;etc))
```

So, don't load friend's middleware through :middleware, just wrap the routes with it.

**Comment by ddellacosta** [comment]
As far as your issue--isn't this a general friend/lib-noir issue?  Is there something you think needs to be addressed by friend-oauth2 here?

**Comment by hjrnunes** [comment]
Perhaps you're right. I guess the reason I wrote here was because I was using Friend only with friend-oauth and the tutorial in the wiki explains how to typically set it up with Ring.

**Comment by bzg** [comment]
Yes, it probably needs to be addressed in friend - thanks for the heads up @hjrnunes!

**Comment by ddellacosta** [comment]
Yeah, I mean obviously if it helps someone to have a comment here or in the wiki I'm all for it, just wanted to be clear on that.  Gonna close this unless you object.  If you think that adding a note about this in the wiki makes sense go for it--just make sure you clarify that it's not specifically a friend-oauth2 issue.
